apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-nsqd
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.docker_tag }}
spec:
  serviceName: drycc-nsqd
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: drycc-nsqd
  template:
    metadata:
      labels:
        app: drycc-nsqd
    spec:
      serviceAccount: drycc-nsqd
      containers:
        - name: drycc-nsqd
          image: {{.Values.docker_registry}}{{.Values.org}}/nsqd:{{.Values.docker_tag}}
          imagePullPolicy: {{.Values.pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
          resources:
            limits:
{{- if (.Values.limits_cpu) }}
              cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
              memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
          command: ["/opt/nsqd/bin/start-nsqd", "-http-address", ":{{.Values.http_port}}", "-tcp-address", ":{{.Values.tcp_port}}"]
          ports:
          - containerPort: {{.Values.http_port}}
            name: http
            protocol: TCP
          - containerPort: {{.Values.tcp_port}}
            name: transport
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: {{.Values.http_port}}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: {{.Values.http_port}}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
