apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-nsqd
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  serviceName: drycc-nsqd
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: drycc-nsqd
  template:
    metadata:
      labels:
        app: drycc-nsqd
    spec:
      serviceAccount: drycc-nsqd
      containers:
        - name: drycc-nsqd
          image: {{.Values.image_registry}}/{{.Values.org}}/nsqd:{{.Values.image_tag}}
          imagePullPolicy: {{.Values.image_pull_policy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
          resources:
            limits:
{{- if (.Values.limits_cpu) }}
              cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
              memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
          command: ["/opt/nsqd/bin/start-nsqd", "-http-address", ":4151", "-tcp-address", ":4150"]
          ports:
          - containerPort: 4151
            name: http
            protocol: TCP
          - containerPort: 4150
            name: transport
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 4151
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: 4151
            initialDelaySeconds: 5
            timeoutSeconds: 1
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
