apiVersion: v1
kind: Service
metadata:
  name: drycc-nsqd
  labels:
    heritage: drycc
    app: drycc-nsqd
spec:
  clusterIP: None
  ports:
  - port: {{.Values.tcpPort}}
    name: transport
    targetPort: transport
  - port: {{.Values.httpPort}}
    name: http
    targetPort: http
  selector:
    app: drycc-nsqd
