apiVersion: v1
kind: Service
metadata:
  name: drycc-nsqd
  labels:
    heritage: drycc
    app: drycc-nsqd
spec:
  ports:
  - port: 4151
    name: http
    targetPort: http
  - port: 4150
    name: transport
    targetPort: transport
  selector:
    app: drycc-nsqd
