apiVersion: v1
kind: Service
metadata:
  name: drycc-nsqd
  labels:
    heritage: drycc
    app: drycc-nsqd
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.tcp_port }}
    name: transport
    targetPort: transport
  - port: {{ .Values.http_port }}
    name: http
    targetPort: http
  selector:
    app: drycc-nsqd
